export type Book = {
  title: string;
  link: string;
  author: string;
  pubDate: string;
  description: string;
  isbn13: string;
  itemId: number;
  priceSales: number;
  priceStandard: number;
  stockStatus: string;
  mileage: number;
  cover: string;
  categoryId: number;
  categoryNumber: string;
  publisher: string;
  adult: boolean;
  subTitle: string | null;
  originalTitle: string | null;
  itemPage: number;
};
